import { Link } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Header } from "@/components/Header";
import { ArrowLeft, FileText, AlertCircle, Scale, CheckCircle, XCircle, Shield } from "lucide-react";

const TermsOfServicePage = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <div className="container py-8 space-y-8 max-w-4xl">
        {/* Back Button */}
        <Button variant="ghost" asChild className="mb-4">
          <Link to="/" className="flex items-center gap-2">
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
        </Button>

        {/* Hero Section */}
        <div className="space-y-4">
          <div className="flex items-center gap-3 mb-4">
            <FileText className="h-10 w-10 text-primary" />
            <h1 className="text-3xl sm:text-4xl font-bold">Terms of Service</h1>
          </div>
          <p className="text-muted-foreground">
            Last Updated: November 4, 2025
          </p>
          <p className="text-muted-foreground">
            Welcome to ToolCheetah! By accessing and using our website and tools, you agree to be bound by these 
            Terms of Service. Please read them carefully.
          </p>
        </div>

        {/* Quick Summary */}
        <Card className="bg-primary/5 border-primary/20">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5" />
              Quick Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            <p className="text-sm text-muted-foreground">
              ToolCheetah provides free online tools "as-is" without warranties. You're responsible for how you 
              use our tools and any content you process. We're not liable for any damages arising from your use 
              of our services. Use responsibly and legally.
            </p>
          </CardContent>
        </Card>

        {/* Acceptance of Terms */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Scale className="h-5 w-5 text-blue-500" />
              1. Acceptance of Terms
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-sm text-muted-foreground">
              By accessing or using ToolCheetah ("we," "us," or "our"), you agree to be bound by these Terms of 
              Service and all applicable laws and regulations. If you do not agree with any of these terms, you 
              are prohibited from using or accessing this site.
            </p>
            <p className="text-sm text-muted-foreground">
              We reserve the right to modify these terms at any time. Your continued use of the service after 
              changes are posted constitutes acceptance of those changes.
            </p>
          </CardContent>
        </Card>

        {/* Use of Services */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-green-500" />
              2. Use of Services
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <h4 className="font-semibold">2.1 Free Access</h4>
              <p className="text-sm text-muted-foreground">
                All tools and services on ToolCheetah are provided free of charge. We do not require registration 
                or payment to use our tools.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">2.2 Permitted Use</h4>
              <p className="text-sm text-muted-foreground">
                You may use our tools for any lawful purpose, including personal, educational, and commercial projects. 
                You are free to use the results generated by our tools in your own work without attribution.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">2.3 Age Requirement</h4>
              <p className="text-sm text-muted-foreground">
                Our services are available to users of all ages. However, if you are under 10 years old, you should 
                use our services with parental guidance.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Prohibited Activities */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <XCircle className="h-5 w-5 text-red-500" />
              3. Prohibited Activities
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-sm text-muted-foreground">
              You agree not to engage in any of the following prohibited activities:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-2 ml-4">
              <li>Using our tools for any illegal or unauthorized purpose</li>
              <li>Attempting to gain unauthorized access to our systems or networks</li>
              <li>Transmitting viruses, malware, or other malicious code</li>
              <li>Interfering with or disrupting the service or servers</li>
              <li>Using automated systems (bots, scrapers) to access the service in a way that sends more requests 
                than a human can reasonably produce</li>
              <li>Attempting to reverse engineer, decompile, or disassemble any part of the service</li>
              <li>Removing or modifying any copyright, trademark, or proprietary notices</li>
              <li>Using our tools to process or distribute illegal content</li>
              <li>Impersonating any person or entity or falsely stating your affiliation with a person or entity</li>
            </ul>
          </CardContent>
        </Card>

        {/* Intellectual Property */}
        <Card>
          <CardHeader>
            <CardTitle>4. Intellectual Property</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <h4 className="font-semibold">4.1 Our Content</h4>
              <p className="text-sm text-muted-foreground">
                The website design, layout, code, and original content are owned by ToolCheetah and are protected 
                by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, 
                or create derivative works from our website without explicit permission.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">4.2 Your Content</h4>
              <p className="text-sm text-muted-foreground">
                You retain all rights to any content you upload or process using our tools. We do not claim ownership 
                of your content. Since all processing happens in your browser, your content never reaches our servers.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">4.3 Generated Content</h4>
              <p className="text-sm text-muted-foreground">
                Any content generated by our tools (converted files, calculated results, etc.) belongs to you. You 
                are free to use it however you wish, including for commercial purposes.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Disclaimers */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-yellow-500" />
              5. Disclaimers and Limitations of Liability
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              <h4 className="font-semibold">5.1 "As-Is" Service</h4>
              <p className="text-sm text-muted-foreground">
                Our tools are provided "as-is" without warranties of any kind, either express or implied. We do not 
                guarantee that our tools will be error-free, uninterrupted, or meet your specific requirements.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">5.2 Accuracy of Results</h4>
              <p className="text-sm text-muted-foreground">
                While we strive to provide accurate tools, we cannot guarantee the accuracy, completeness, or 
                reliability of any results generated by our tools. You are responsible for verifying any important 
                calculations or conversions independently.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">5.3 No Professional Advice</h4>
              <p className="text-sm text-muted-foreground">
                Our tools are for informational purposes only and do not constitute professional advice (legal, 
                financial, medical, or otherwise). Always consult with qualified professionals for important decisions.
              </p>
            </div>

            <div className="space-y-3">
              <h4 className="font-semibold">5.4 Limitation of Liability</h4>
              <p className="text-sm text-muted-foreground">
                To the fullest extent permitted by law, ToolCheetah shall not be liable for any indirect, incidental, 
                special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred 
                directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
              </p>
              <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
                <li>Your use or inability to use our services</li>
                <li>Any unauthorized access to or use of our servers</li>
                <li>Any interruption or cessation of transmission to or from our services</li>
                <li>Any bugs, viruses, or other harmful code that may be transmitted through our services</li>
                <li>Any errors or omissions in any content or results generated by our tools</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        {/* Third-Party Links and Services */}
        <Card>
          <CardHeader>
            <CardTitle>6. Third-Party Links and Services</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-sm text-muted-foreground">
              Our website may contain links to third-party websites or services that are not owned or controlled by 
              ToolCheetah. We have no control over and assume no responsibility for the content, privacy policies, 
              or practices of any third-party websites or services.
            </p>
            <p className="text-sm text-muted-foreground">
              Some of our tools may use external APIs (such as currency rates or website performance testing). When 
              using these tools, the data you input may be transmitted to these third-party services. We recommend 
              reviewing their terms and privacy policies.
            </p>
          </CardContent>
        </Card>

        {/* Advertising */}
        <Card>
          <CardHeader>
            <CardTitle>7. Advertising</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Our website may display third-party advertisements. We use advertising to keep our tools free for 
              everyone. Advertisers are responsible for ensuring their ads comply with applicable laws. We are not 
              responsible for the content or accuracy of advertisements or the products/services they promote.
            </p>
          </CardContent>
        </Card>

        {/* Data and Privacy */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Shield className="h-5 w-5 text-purple-500" />
              8. Data and Privacy
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              Your use of our services is also governed by our Privacy Policy. All tools run locally in your browser, 
              and we do not collect or store the content you process. Please review our <Link to="/privacy-policy" 
              className="text-primary hover:underline">Privacy Policy</Link> to understand how we handle your information.
            </p>
          </CardContent>
        </Card>

        {/* Termination */}
        <Card>
          <CardHeader>
            <CardTitle>9. Termination</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              We reserve the right to terminate or suspend access to our services immediately, without prior notice 
              or liability, for any reason whatsoever, including if you breach these Terms of Service. Upon termination, 
              your right to use the service will immediately cease.
            </p>
          </CardContent>
        </Card>

        {/* Governing Law */}
        <Card>
          <CardHeader>
            <CardTitle>10. Governing Law</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              These Terms shall be governed and construed in accordance with the laws of your jurisdiction, without 
              regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms 
              will not be considered a waiver of those rights.
            </p>
          </CardContent>
        </Card>

        {/* Changes to Terms */}
        <Card>
          <CardHeader>
            <CardTitle>11. Changes to Terms</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              We reserve the right to modify or replace these Terms at any time at our sole discretion. The "Last 
              Updated" date at the top will be revised when changes are made. Your continued use of the service after 
              any changes constitutes acceptance of the new Terms.
            </p>
          </CardContent>
        </Card>

        {/* Severability */}
        <Card>
          <CardHeader>
            <CardTitle>12. Severability</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions will 
              remain in full force and effect. The invalid or unenforceable provision will be replaced with a valid 
              provision that most closely matches the intent of the original provision.
            </p>
          </CardContent>
        </Card>

        {/* Contact */}
        <Card className="bg-muted/30">
          <CardHeader>
            <CardTitle>13. Contact Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <p className="text-sm text-muted-foreground">
              If you have any questions about these Terms of Service, please contact us through our social media channels.
            </p>
            <Button variant="outline" asChild>
              <a href="https://www.instagram.com/toolcheetah" target="_blank" rel="noopener noreferrer">
                Contact Us on Instagram
              </a>
            </Button>
          </CardContent>
        </Card>

        {/* Acknowledgment */}
        <Card className="bg-primary/5 border-primary/20">
          <CardContent className="py-6">
            <p className="text-sm text-muted-foreground text-center">
              By using ToolCheetah, you acknowledge that you have read, understood, and agree to be bound by these 
              Terms of Service and our Privacy Policy.
            </p>
          </CardContent>
        </Card>

        {/* Bottom CTA */}
        <div className="text-center pt-4">
          <Button asChild size="lg">
            <Link to="/">Start Using Our Tools</Link>
          </Button>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
